version: '3.8'
services:
  mysql:
    image: 'mysql:8.0'
    container_name: tanaka-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: tanaka
      MYSQL_USER: tanaka
      MYSQL_PASSWORD: ${SQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${SQL_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7
    container_name: tanaka-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  tanaka:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    environment:
      SQL_HOST: mysql
      SQL_DATABASE: tanaka
      SQL_USERNAME: tanaka
      SQL_PASSWORD:
      DISCORD_TOKEN:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data:
    name: tanaka-mysql
  redis-data:
    name: tanaka-redis
