version: '3.8'
services:
  mysql:
    image: 'mysql:8.0'
    container_name: tanaka-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - '3306:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
  tanaka:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SQL_HOST:
      SQL_DATABASE:
      SQL_USERNAME:
      SQL_PASSWORD:
      DISCORD_TOKEN:
    depends_on:
      - mysql
volumes:
  mysql-data:
    name: tanaka-mysql
