export enum SettingsTypes {
  AUTOMATIC_SUMMON_TIMERS = 'Automatic Summon Timers',
  HIGH_TIER_PING_ROLE = 'High Tier Ping Role',
  HIGH_TIER_PING_MESSAGE = 'High Tier Ping Message',
  C_AUCTION_CHANNEL = 'Common Auction Channel',
  R_AUCTION_CHANNEL = 'Rare Auction Channel',
  SR_AUCTION_CHANNEL = 'Super Rare Auction Channel',
  SSR_AUCTION_CHANNEL = 'Super Super Rare Auction Channel',
  UR_AUCTION_CHANNEL = 'Ultra Rare Auction Channel',
  APPROVAL_AUCTION_CHANNEL = 'Approval Auction Channel',
  QUEUE_AUCTION_CHANNEL = 'Queue Auction Channel',
  MAX_AUCTIONS_PER_USER = 'Max Auctions Per User',
  MAX_C_AUCTIONS_PER_QUEUE = 'Max Common Auctions Per Queue',
  MAX_R_AUCTIONS_PER_QUEUE = 'Max Rare Auctions Per Queue',
  MAX_SR_AUCTIONS_PER_QUEUE = 'Max Super Rare Auctions Per Queue',
  MAX_SSR_AUCTIONS_PER_QUEUE = 'Max Super Super Rare Auctions Per Queue',
  MAX_UR_AUCTIONS_PER_QUEUE = 'Max Ultra Rare Auctions Per Queue',
  AUCTION_LIFETIME_MINUTES = 'Auction Lifetime',
}
