export enum SettingsTypes {
  AUTOMATIC_SUMMON_TIMERS = 'Automatic Summon Timers',
  AUTOMATIC_SUMMER_TIMERS = 'Automatic Summer Timers',
  AUTOMATIC_BOX_TIMERS = 'Automatic Box Timers',
  AUTOMATIC_DATE_TIMERS = 'Automatic Date Timers',
  AUTOMATIC_CLAN_SUMMONS = 'Automatic Clan Summons',
  ENABLE_AUTOMATIC_TIMERS_AS_DEFAULT = 'Enable Automatic Timers as Default',
  HIGH_TIER_PING_ROLE = 'High Tier Ping Role',
  HIGH_TIER_PING_MESSAGE = 'High Tier Ping Message',
  REGULAR_TIER_PING_ROLE = 'Regular Tier Ping Role',
  REGULAR_TIER_PING_MESSAGE = 'Regular Tier Ping Message',
  CLAN_WAR_ATTACK_TARGET = 'Clan war Attack Target',
  CLAN_WAR_HEAL_TARGET = 'Clan war Heal Target',
  CLAN_WAR_SHIELD_TARGET = 'Clan war Shield Target',
  PHOENIX_REVIVAL_PRIORITY = 'Phoenix Revival Priority',
  DIVINE_AEGIS_PRIORITY = 'Divine Aegis Priority',
  CHAOS_ORB_PRIORITY = 'Chaos Orb Priority',
  LIFE_SURGE_PRIORITY = 'Life Surge Priority',
  MIRROR_FORCE_PRIORITY = 'Mirror Force Priority',
  INFERNO_BLAST_PRIORITY = 'Inferno Blast Priority',
  REGENERATION_PRIORITY = 'Regeneration Priority',
  MYSTIC_WARD_PRIORITY = 'Mystic Ward Priority',
  LIGHTNING_STRIKE_PRIORITY = 'Lightning Strike Priority',
  HEALING_LIGHT_PRIORITY = 'Healing Light Priority',
  STONE_SHIELD_PRIORITY = 'Stone Shield Priority',
  FROST_SHARD_PRIORITY = 'Frost Shard Priority',
}
